- name: variables
  hosts: local
  connection: local
  vars: # These are play level variables
    COURSE_NAME: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar"
  tasks:
  - name: Print Task level variaables
    vars: # These are Task level variables
      COURSE_NAME: "DevSecOps with AWS"
      DURATION: "150HRS"
      TRAINER: "Chouda Reddy"
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE_NAME }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"
  tasks:
  - name: Print play level variaables
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE_NAME }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"