- name: "Variables from inventory"
  hosts: local
  connection: local
  tasks:
  - name: Print the variables from inventory.
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE_NAME }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"