- name: "Variables from inventory"
  hosts: web
  tasks:
  - name: Print the variables from inventory.
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"