- name: "Variables from arguments"
  hosts: local
  connection: local
  tasks:
  - name: Print the variables from arguments
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"