- name: Check the value is greater than 10 or not.
  hosts: local
  connection: local
  vars_prompt:
      name: value
      prompt: "Enter a value to check if it is greater than, less than, or equal to 10"
      private: false
      type: int
  tasks:
    - name: Print if the value is greater than 10.
      ansible.builtin.debug:
        msg: "The value {{ value }} is greater than 10."
      when: value > 10
    - name: Print if the value is less than 10.
      ansible.builtin.debug:
        msg: "The value {{ value }} is less than 10."
      when: value < 10
    - name: Print if the value is equal to 10.
      ansible.builtin.debug:
        msg: "The value {{ value }} is equal to 10."
      when: value == 10