- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Manvi') }}"
  - name: Convert string to list
    vars:
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"
  - name: Convert map to list
    vars:
      course:
        name: ansible
        duration: 30
        trainer: Manvi
    ansible.builtin.debug:
      msg: "Course info {{ course | dict2items }}"
  - name: Convert list to map
    tags:
    - convert_list_to_map
    vars:
      course:
      - { 'key': 'name', 'value': 'ansible' }
      - { 'key': 'duration', 'value': 30 }
      - { 'key': 'trainer', 'value': 'Manvi' }
    ansible.builtin.debug:
      msg: "Course info {{ course | items2dict }}"
  - name: Check ip address is valid or not
    vars:
      ip: "1234.2345.3456.4567"
    ansible.builtin.debug:
      msg: "IP address is valid: {{ ip | ansible.utils.ipaddr }}"
  name: convert to uppercase
  tags:
  - uppercase
  vars:
    text: "hello world"
  ansible.builtin.debug:
    msg: "Uppercase text: {{ text | upper }}"