- name: Create ec2 Instances and Route53
  hosts: localhost
  connection: local
  vars:
    subnet_id: subnet-06537747f3b689663
    sg_id: sg-0a89d0b1ae02b30dd
    ami_id: ami-09c813fb71547fc4f
    instance_id: t2.mirco
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Create AWS Python Libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - boto3
      - botocore
  - name: Create ec2 Instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "{{ instance_id }}"
      image_id: "{{ ami_id }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"